# set prompt
source ~/.bash/git-prompt.sh
PS1='\[\e[0;34m\]\t <\h> $(__git_ps1 " (%s)") \[\e[m\]
        \[\e[0;35m\] \W \$ \[\e[m\] \[\e[0;37m\]'

# get the vim shortcuts in bash
set -o vi

###################
### ENVIRONMENT ###
###################

# first see which server I'm on

# if [ "$HOSTNAME" = "harmattan.cosmo.fas.nyu.edu" ]; then
#   export pathext="/harmattanhome";
# elif [ "$HOSTNAME" = "SIROCCO.COSMO.FAS.NYU.EDU" ]; then
#   export pathext="/siroccohome";
# else
#   export pathext="";
# fi

export pathext="";

## Python things ##

# Get the path to my new modules
PYTHONPATH=$HOME$pathext/lib:${PYTHONPATH}
export PYTHONPATH

# virtualenvwrapperstuff
export WORKON_HOME=$HOME$pathext/virtualenvs
export PROJECT_HOME=$HOME/dev
source $HOME$pathext/bin/virtualenvwrapper.sh

# export GOROOT=$HOME/Software/go

# PATH=/usr/lib/postgresql/9.1/bin:$PATH
# export PATH

# adding opt stuff
# PATH=/opt/calibre:$PATH
# export LC_ALL=C

if [ "$HOSTNAME" = "broiler" ]; then

  PATH=/usr/local/astrometry/bin:$PATH:$GOROOT/bin
  export PATH

  # piece for lein for slimv
  PATH=~/.bash/opt:$PATH
  export PATH

  # adding java so that lein works on broiler
  JAVA_HOME=~/.local/usr/java/jdk1.7.0_17
  PATH=$PATH:$JAVA_HOME/bin
  export JAVA_HOME
  export PATH

  # more PATH stuff for broiler

  export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/wcslib-4.7/lib

  export PATH=~/bashscripts:$HOME/astrometry/util:$HOME/astrometry/blind:$PATH

  export SBCL_INSTALL=$HOME/opt/mysbcl
  PATH=$SBCL_INSTALL/bin:$PATH
  export SBCL_HOME=$SBCL_INSTALL/lib/sbcl
  export PATH

  export DISPLAY=:0

  PYTHONPATH=${PYTHONPATH}:/home/kilian:/home/kilian/tractor:/home/kilian/tractor/tractor
  export PYTHONPATH

  # Include basemap
  PYTHONPATH=${PYTHONPATH}:/home/kilian/download/basemap-1.0.5/lib
  export PYTHONPATH
  # end broiler stuff
fi

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
fi

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    eval "$(dircolors -b ~/.bash/dircolors/dircolors.256dark)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    #alias fgrep='fgrep --color=auto'
    #alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

alias ..='cd ..'
alias ....='cd ../..'
alias ......='cd ../../..'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# new vim alias for custom install
alias vim=$HOME$pathext/bin/vim

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# stuff for ruby
# export PATH="$HOME/bin:$HOME/.gem/bin:$PATH"
# export RUBYLIB="$HOME/lib:$RUBYLIB"
# export GEM_HOME="$HOME/.gem"
# export GEM_PATH="/usr/lib/ruby/1.8:$GEM_HOME"
# alias gem="nice -n19 ~/bin/gem"

# PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
# [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/users/kww231/.rvm/rubies/ruby-2.1.2/lib


# Path stuff

# have the local environment be the first goto for the PATH and LD_LIBRARY_PATH
export PATH=$HOME$pathext/bin:$PATH

# and lib and include dirs
export LD_LIBRARY_PATH=$HOME$pathext/lib64:$HOME$pathext/lib:$LD_LIBRARY_PATH

# if [ "$HOSTNAME" = "harmattan" ]; then
#   export LD_LIBRARY_PATH=/home/users/kww231/harmattanhome/opt/OpenBLAS/lib:$LD_LIBRARY_PATH
# fi

export C_INCLUDE_PATH=$HOME$pathext/include:$C_INCLUDE_PATH

export CPLUS_INCLUDE_PATH=$HOME$pathext/include:$CPLUS_INCLUDE_PATH

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# java stuff
# JAVA_HOME=$HOME/java/jdk1.8.0_45
# PATH=$JAVA_HOME/bin:$PATH
# export JAVA_HOME
# export PATH

# hadoopy
# export PATH=$PATH:$HOME/src/hadoop-2.6.0/bin

# julia playground
export PATH=$HOME/.playground/bin:$PATH
